name: 'Run FastAPI server in background'
description: 'Reusable action to run the FastAPI server in background on port 8000.'
runs:
  using: composite
  steps:
  - name: Install uv
    uses: astral-sh/setup-uv@v8
    with:
      enable-cache: true
  - name: Install Python dependencies
    shell: bash
    run: uv sync --all-extras --dev
  - name: Run server in background
    shell: bash
    run: uv run fastapi run app/main.py --port 8000 &
  - name: Generate OpenAPI document
    shell: bash
    run: curl -f http://localhost:8000/openapi.json -o openapi.json