services:
  tika:
    image: apache/tika:3.0.0.0-full
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "-O", "/dev/null", "http://localhost:9998/tika" ]
      interval: 30s
      timeout: 20s
      retries: 3
  mandolin:
    image: ghcr.io/piroguetoolsuite/mandolin:main
    restart: unless-stopped
    ports:
      - "0.0.0.0:8888:8000"
    depends_on:
      tika:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "-O", "/dev/null", "http://localhost:8000/" ]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      - TIKA_URL=http://tika:9998/
      - MAX_FILE_SIZE=250000000  # 250MB