[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mandolin"
version = "1.2.0"
description = "Micro-service to analyze and convert files"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "GPL-3.0"}
authors = [
    {name = "Defensive Lab Agency"},
]
maintainers = [
    {name = "Defensive Lab Agency"},
]
keywords = ["fastapi", "microservice", "analysis", "conversion", "tika", "yara"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
dependencies = [
    "fastapi[standard]==0.128.8",
    "uvicorn==0.44.0",
    "django-environ==0.13.0",
    "tika-client==0.11.0",
    "markdownify==1.2.2",
    "python-multipart==0.0.27",
    "python-slugify==8.0.4",
    "yara-python==4.5.4",
    "pillow==12.2.0",
    "python-magic==0.4.27",
]

[project.optional-dependencies]
dev = [
    "typing_extensions",
    "watchfiles",
    "schemathesis>=4.15.0",
]

[tool.uv]
dev-dependencies = [
    "typing_extensions",
    "watchfiles",
    "schemathesis",
]

[project.urls]
Homepage = "https://pts-project.org"
Documentation = "https://pts-project.org/docs/pirogue/overview/"
Repository = "https://github.com/PiRogueToolSuite/mandolin"

[tool.setuptools.packages.find]
where = ["."]
include = ["app*", "mandolin*"]
